=== hussachai/easyexecutor/src/test/resources/easyexecutor.dtd
<!ELEMENT easy-executor (import*, system-properties?, user-properties*,classpath?, application?) >
<!ATTLIST easy-executor single-instance (true|false) #IMPLIED>
<!ATTLIST easy-executor locale NMTOKEN #IMPLIED>

<!ELEMENT import EMPTY>
<!ATTLIST import location CDATA #REQUIRED>

<!ELEMENT property (#PCDATA) >
<!ATTLIST property key CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>

<!ELEMENT system-properties (property*) >
<!ATTLIST system-properties location CDATA #IMPLIED>

<!ELEMENT user-properties (property*) >
<!ATTLIST user-properties name NMTOKEN #REQUIRED>
<!ATTLIST user-properties location CDATA #IMPLIED>
<!ATTLIST user-properties extends NMTOKEN #IMPLIED>

<!ELEMENT classpath (classes*, lib*) >
<!ELEMENT classes (#PCDATA) >
<!ATTLIST classes path CDATA #REQUIRED>
<!ELEMENT lib (#PCDATA) >
<!ATTLIST lib path CDATA #REQUIRED>

<!ELEMENT application (name?, version?, description?, logger?,cron?, beans) >
<!ATTLIST application id NMTOKEN #REQUIRED>
<!ATTLIST application mode NMTOKEN #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT logger EMPTY>
<!ATTLIST logger impl (log4j|jdk ) "log4j">
<!ATTLIST logger config CDATA #REQUIRED>

<!ELEMENT cron EMPTY>
<!ATTLIST cron expression CDATA #REQUIRED>

<!ELEMENT beans (bean+) >

<!ELEMENT bean (method*) >
<!ATTLIST bean class CDATA #REQUIRED>
<!ATTLIST bean id ID #REQUIRED>

<!ELEMENT method (arg*) >
<!ATTLIST method name NMTOKEN #REQUIRED>

<!ELEMENT arg (#PCDATA) >
<!ATTLIST arg type NMTOKEN #REQUIRED>
<!ATTLIST arg value CDATA #IMPLIED>

=== hussachai/easyexecutor/src/test/resources/bar-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE easy-executor SYSTEM "easyexecutor.dtd">
<easy-executor single-instance="true" locale="th_TH">	
	
	<import location="classpath:foo-config.xml"/>
	
	<system-properties location="classpath:system.properties">
		<property key="siberhus.message" value="More important message"/>
		<property key="siberhus.owner" value="Hussachai Puripunpinyo"/>
	</system-properties>
	
	<user-properties name="bar" extends="foo">
		<property key="name" value="Bar"/>
	</user-properties>
	
	<user-properties name="foobar">
		<property key="name" value="FooBar"/>
	</user-properties>
	
	<classpath>
		<!--
		<classes path=""></classes>
		 -->
		<lib path="lib"></lib>
	</classpath>
	
	<application id="bar-app" mode="test">
		<name>Bar Application</name>
		<version>0.1</version>
		<description>
			Trivial Description
		</description>
		
		<logger impl="log4j" config="classpath:log4j.properties"/>
		<cron expression="* * * * *"/>
		<beans>
			<bean id="foobar" class="com.siberhus.easyexecutor.test.FooBarBean">
				<method name="doSomethingWithParams">
					<arg type="java.lang.Integer" value="${1}"/>
					<arg type="java.lang.Integer" value="${2}"/>
					<arg type="java.util.Date" value="${3}"/>
					<arg type="java.lang.String" value="Hello"/>
				</method>
			</bean>
		</beans>
		<!-- if method attribute is not specified, main method will be used instead -->
	</application>
	
</easy-executor>

<!--
	Next release:
		- Support native parameter binding 
 -->

=== hussachai/easyexecutor/src/test/resources/testapp-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE easy-executor SYSTEM "easyexecutor.dtd">
<easy-executor single-instance="false" locale="en_US">	
	
	<application id="foo-app" mode="test">
		<name>Test Application</name>
		<version>0.1</version>
		<description>
			Trivial Description
		</description>
		<beans>
			<bean id="foobar.doSomething" class="com.siberhus.easyexecutor.test.FooBarBean">
				<method name="doSomething"/>
			</bean>
		</beans>
	</application>
</easy-executor>

=== hussachai/easyexecutor/src/test/resources/foo-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE easy-executor SYSTEM "easyexecutor.dtd">
<easy-executor single-instance="true" locale="en_US">	
	
	<user-properties name="foo" location="classpath:foo.properties"/>
	<classpath>
		<classes path="directory1"></classes>
		<classes path="directory2"></classes>
		<lib path="directory3"></lib>
	</classpath>
	<application id="foo-app" mode="test">
		<name>Foo Application</name>
		<version>0.1</version>
		<description>
			Trivial Description
		</description>
		<beans>
			<bean id="foobar" class="com.siberhus.easyexecutor.test.FooBarBean" />
		</beans>
		<!-- if method attribute is not specified, main method will be used instead -->
	</application>
</easy-executor>
